### ISSUE TITLE
Collision Error

### ISSUE THREAD

**Issue by bartlomiejduda** [Ekey/JC.ARC.Tool#1]
For some reson I'm getting this weird collision error:

```
Just Cause TAB/ARC Unpacker
(c) 2021 Ekey (h4x0r) / v1.0.0.0

[COLLISION]: models\characters\animations\drunk\mhstd_drunk.anim <-> models\characters\animations\npcmoves\drunk\mhstd_drunk.anim

Wyjatek nieobsluzony: System.ArgumentException: Element o tym samym kluczu zostal juz dodany.
   w System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   w System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   w JC.Unpacker.TabHashList.iLoadProject() w C:\Users\User\Desktop\SARC\JC.ARC.Tool-main\JC.Unpacker\JC.Unpacker\FileSystem\Package\TabHashList.cs:wiersz 38
   w JC.Unpacker.TabUnpack.iDoIt(String m_TabFile, String m_DstFolder) w C:\Users\User\Desktop\SARC\JC.ARC.Tool-main\JC.Unpacker\JC.Unpacker\FileSystem\Package\TabUnpack.cs:wiersz 15
   w JC.Unpacker.Program.Main(String[] args) w C:\Users\User\Desktop\SARC\JC.ARC.Tool-main\JC.Unpacker\JC.Unpacker\Program.cs:wiersz 39
```

I'm executing tool like this:
`C:\Users\User\Desktop\SARC\JC.ARC.Tool-main\JC.Unpacker\JC.Unpacker\bin\Release>C:\Users\User\Desktop\SARC\JC.ARC.Tool-main\JC.Unpacker\JC.Unpacker\bin\Release\JC.Unpacker.exe "D:\GRY\Just Cause 1\Archives\pc.tab" "D:\GRY\Just Cause 1\Archives\out2"`

Do you know what can be the issue here and how to fix it?

**Comment by Ekey** [comment]
If you added new file names to the project file, make sure there are no duplicates. Best way by using Notepad++ > Edit -> Line Operations -> Remove Duplicate Lines

**Comment by bartlomiejduda** [comment]
Fun thing is that I didn't add any new file names. :) I've just compiled the code and run it as it is.

And this "Remove Duplicate Lines" function doesn't change a file at all.

**Comment by bartlomiejduda** [comment]
Maybe there are some differences in the ARC/TAB files?
Here is the checksum for my "pc.tab" file and sizes for other files:

![screenshot000009](https://github.com/Ekey/JC.ARC.Tool/assets/5502283/87dcfe8d-1d3c-4244-b3a8-556d9cbe9a70)

**Comment by Ekey** [comment]
Hmm... Try this batch file [JC.Unpacker.zip](https://github.com/Ekey/JC.ARC.Tool/files/13327894/JC.Unpacker.zip) . Copy to the executable file and run it.

Variant #2 - Copy Unpacker files from desktop to local disk for example to D:\Tool

**Comment by bartlomiejduda** [comment]
Unfortunately it gives me the same error.

**Comment by Ekey** [comment]
Upload TAB file for me, i'll check whats wrong.

**Comment by bartlomiejduda** [comment]
Sure. Here you go:
[pc.zip](https://github.com/Ekey/JC.ARC.Tool/files/13329169/pc.zip)

**Comment by Ekey** [comment]
Ok, I rebuilt the list and it should work now :)

**Comment by bartlomiejduda** [comment]
It works now. Thanks.
