### ISSUE TITLE
Expanded file-list

### ISSUE THREAD

**Issue by LukeJC3** [Ekey/JC.ARC.Tool#2]
First off, thank you a lot for making this!

I downloaded the JC1 demo and saw it comes with a file-list. I merged it into yours for almost an additional 2000 file paths!
Not sure if you want to add it, but if you want to, here you go:
https://drive.google.com/file/d/1WdQAEDyuEIipTUaSQHoMQduMfU0fCjkN/view?usp=sharing

I also noticed it doesn't like it when 2 files are named the same, even though they are in different paths, so I had to remove a few things to make it unpack successfully

**Comment by Ekey** [comment]
Thanks!

> I also noticed it doesn't like it when 2 files are named the same, even though they are in different paths, so I had to remove a few things to make it unpack successfully

Full paths are not required here since the hashes are based only on the file name without the path. Example

**models\characters\animations\vehicles\bike_bikestuntto_mhbike.anim** -> **bike_bikestuntto_mhbike.anim**

You can delete these paths :)
